export let languages_dict = {
  "pl": {

    // Basic
    "personal_informations": "Informacje personalne",
    "socials_and_websites": "Profile społecznościowe i strony www",
    "employment_history": "Historia zatrudnienia",
    "education_and_courses": "Edukcja i kursy",
    "skills": "Umiejętności",
    "languages": "Języki",
    "references": "Referencje",
    "custom": "Dodatkowa aktywność",
    "rodo": "Klauzula RODO",
    "job_title": "Tytuł zawodowy",
    "add_photo": "Dodaj zdjęcie",
    "first_name": "Imię",
    "last_name": "Nazwisko",
    "email": "Email",
    "phone": "Telefon",
    "more_datails": "Więcej szczegółów",
    "less_datails": "Mniej",
    "professional_summary": "Podsumowanie zawodowe",
    "contact": "Kontakt",
    "country": "Państwo",
    "city": "Miasto",
    "street_and_number": "Ulica i numer domu",
    "postcode": "Kod pocztowy",
    "place_of_birth": "Miejsce urodzenia",
    "date_of_birth": "Data urodzenia",
    "hobbies": "Zainteresowania",
    "address": "Adres",
    "socials_and_websites_right": "Profile społecznościowe",
    "school": "Uczelnia/szkoła",
    "direction": "Kierunek",

    // Components
    "add": "Dodaj",
    "employer": "Pracodawca",
    "from": "Od",
    "to": "Do",
    "description": "Opis",
    "skill": "Umiejętność",
    "level": "Poziom",
    "language": "Język",
    "referencer_first_and_last_name": "Imię i nazwisko osoby polecającej",
    "company": "Firma",
    "activity": "Aktywność, nazwa książki, itp.",
    "rodo_content": "Treść klauzuli",

    // Components placeholders
    "placeholder_title": "Tytuł",
    "placeholder_job_title": "Assembler Programmer",
    "placeholder_first_name": "Jan",
    "placeholder_last_name": "Kowalski",
    "placeholder_email": "jan@kowalski.pl",
    "placeholder_phone": "+48 111 111 111",
    "placeholder_professional_summary": "Podsumowanie zawodowe",
    "placeholder_country": "Polska",
    "placeholder_city": "Kraków",
    "placeholder_street_and_number": "Jana III Sobieskiego 9",
    "placeholder_postcode": "01-234",
    "placeholder_place_of_birth": "Gdańsk",
    "placeholder_date_of_birth": "7 październik 1987",
    "placeholder_hobbies": "Piłka nożna, podróże",
    "placeholder_link": "facebook.com/jan.kowalski",
    "placeholder_job_title_2": "Kierowca",
    "placeholder_employer": "ABC Sp. z o.o.",
    "placeholder_from": "Styczeń 2020",
    "placeholder_to": "Obecnie",
    "placeholder_school": "Uniwersytet Jagielloński",
    "placeholder_direction": "Ekonomia",
    "placeholder_skill": "Programowanie C++",
    "placeholder_language": "Angielski",
    "placeholder_referencer_first_and_last_name": "Donald Trump",
    "placeholder_referencer_company": "Trump Hotels S.A.",
    "placeholder_referencer_phone": "+48 123 45 67",
    "placeholder_referencer_email": "donald@trump.com",
    "placeholder_custom_activity": "Sekurak Hacking Party 2020",
    "placeholder_rodo_content": "Treść klauzuli",

    // Additional
    "saving": "Zapisuję...",
    "saved": "Zapisane",
    "print_resume": "Drukuj CV",
    "save_and_close": "Zapisz i Zamknij",
  },


  "eng": {

    // Basic
    "personal_informations": "Personal Informations",
    "socials_and_websites": "Social links and websites",
    "employment_history": "Employment history",
    "education_and_courses": "Education and courses",
    "skills": "Skills",
    "languages": "Languages",
    "references": "References",
    "custom": "Additional activity",
    "rodo": "Personal data clause",
    "job_title": "Job title",
    "add_photo": "Add photo",
    "first_name": "First name",
    "last_name": "Last name",
    "email": "Email",
    "phone": "Phone",
    "more_datails": "More details",
    "less_datails": "Less",
    "professional_summary": "Professional summary",
    "contact": "Contact",
    "country": "Country",
    "city": "City",
    "street_and_number": "Street and number",
    "postcode": "Postal code",
    "place_of_birth": "Place of birth",
    "date_of_birth": "Date of birth",
    "hobbies": "Hobbies",
    "address": "Address",
    "socials_and_websites_right": "Social links",
    "school": "School",
    "direction": "Degree",

    // Components
    "add": "Add",
    "employer": "Employer",
    "from": "From",
    "to": "To",
    "description": "Description",
    "skill": "Skill",
    "level": "Level",
    "language": "Language",
    "referencer_first_and_last_name": "Referent's full name",
    "company": "Company",
    "activity": "Activity, book's title, etc.",
    "rodo_content": "Clause content",

    // Components placeholders
    "placeholder_title": "Title",
    "placeholder_job_title": "Assembler Programmer",
    "placeholder_first_name": "John",
    "placeholder_last_name": "Smith",
    "placeholder_email": "john@smith.com",
    "placeholder_phone": "+1 111 111 111",
    "placeholder_professional_summary": "Professional summary",
    "placeholder_country": "USA",
    "placeholder_city": "Los Angeles",
    "placeholder_street_and_number": "Sunrise avenue 7",
    "placeholder_postcode": "12345",
    "placeholder_place_of_birth": "Loas Angeles",
    "placeholder_date_of_birth": "7 October 1987",
    "placeholder_hobbies": "Football, Traveling",
    "placeholder_link": "facebook.com/john.smith",
    "placeholder_job_title_2": "Driver",
    "placeholder_employer": "ABC corp.",
    "placeholder_from": "January 2020",
    "placeholder_to": "Now",
    "placeholder_school": "University of California",
    "placeholder_direction": "Economy",
    "placeholder_skill": "C++ Programming",
    "placeholder_language": "Japanese",
    "placeholder_referencer_first_and_last_name": "Donald Trump",
    "placeholder_referencer_company": "Trump Hotels Corp.",
    "placeholder_referencer_phone": "+1 123 45 67",
    "placeholder_referencer_email": "donald@trump.com",
    "placeholder_custom_activity": "Los Angeles Hacking Party 2020",
    "placeholder_rodo_content": "Clause content",

    // Additional
    "saving": "Saving...",
    "saved": "Saved",
    "print_resume": "Print CV",
    "save_and_close": "Save & close",
  },
}