# Generated by Django 2.1 on 2019-10-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='title',
            new_name='activity',
        ),
    ]
