# Generated by Django 2.1 on 2019-10-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20191012_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/user_photos/'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='street_and_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
