# Generated by Django 2.1 on 2019-10-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20191012_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='activity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='custom',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='custom',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='custom',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='employer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='references',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='references',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='references',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='references',
            name='referents_fullname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social_and_websites',
            name='link',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
