# Generated by Django 2.1 on 2019-10-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20191012_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
