# Generated by Django 2.1 on 2019-11-20 14:13

import cv.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20191012_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/', validators=[cv.validators.file_size_validator]),
        ),
    ]
