# Generated by Django 2.1 on 2019-11-24 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_auto_20191124_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
