# Generated by Django 2.1 on 2019-11-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_remove_social_and_websites_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_and_websites',
            name='cv',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cv.Cv'),
            preserve_default=False,
        ),
    ]
