# Generated by Django 2.1 on 2019-11-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_social_and_websites_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_and_websites',
            name='cv',
        ),
    ]
