# Generated by Django 2.1 on 2019-12-13 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_social_and_websites_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_and_websites',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_and_websites', to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='social_and_websites',
            name='link',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
