# Generated by Django 2.1 on 2019-12-31 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_auto_20191213_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom', to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_and_courses', to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='references',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='cv.Cv'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='cv.Cv'),
        ),
    ]
