# Generated by Django 2.1 on 2019-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_auto_20191231_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_and_websites',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
