# Generated by Django 2.1 on 2020-01-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_auto_20200101_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_and_websites',
            name='idx',
            field=models.IntegerField(default=1000),
        ),
    ]
