# Generated by Django 2.1 on 2020-01-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0018_auto_20200101_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_and_websites',
            name='idx',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
