# Generated by Django 2.1 on 2020-01-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0019_auto_20200101_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_and_websites',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
