# Generated by Django 2.1 on 2020-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0020_auto_20200101_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment_history',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
