# Generated by Django 2.1 on 2020-01-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0021_employment_history_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment_history',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
