# Generated by Django 2.1 on 2020-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0022_auto_20200120_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment_history',
            name='end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employment_history',
            name='start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
