# Generated by Django 2.1 on 2020-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0023_auto_20200208_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='education_and_courses',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='end_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='education_and_courses',
            name='start_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
