# Generated by Django 2.1 on 2020-02-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0024_auto_20200208_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
