# Generated by Django 2.1 on 2020-02-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0025_auto_20200214_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.IntegerField(blank=True),
        ),
    ]
