# Generated by Django 2.1 on 2020-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0026_auto_20200214_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
