# Generated by Django 2.1 on 2020-02-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0029_languages_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
