# Generated by Django 2.1 on 2020-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0030_auto_20200218_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
