# Generated by Django 2.1 on 2020-02-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0031_auto_20200224_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
