# Generated by Django 2.1 on 2020-02-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0036_auto_20200224_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='references',
            name='idx',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
