# Generated by Django 2.1 on 2020-03-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0037_auto_20200226_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
