# Generated by Django 2.1 on 2020-04-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0038_auto_20200304_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='template',
            field=models.IntegerField(blank=True, default=1, max_length=200),
        ),
    ]
