# Generated by Django 2.1 on 2020-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0039_cv_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='template',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
