# Generated by Django 2.1 on 2020-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0041_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end_premium',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_premium',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
