# Generated by Django 2.1 on 2020-04-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0042_auto_20200410_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='end_premium',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='start_premium',
        ),
        migrations.AddField(
            model_name='profile',
            name='premiums',
            field=models.DateTimeField(auto_now_add=True, blank=True),
        ),
    ]
