# Generated by Django 2.1 on 2020-04-24 15:05

import cv.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0043_auto_20200410_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='cv_photo',
            field=models.ImageField(blank=True, upload_to='images/cv_photo/', validators=[cv.validators.file_size_validator]),
        ),
    ]
