# Generated by Django 2.1 on 2020-09-07 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0048_profile_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=200),
        ),
    ]
