# Generated by Django 2.1 on 2020-09-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0049_cv_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodo', models.CharField(blank=True, max_length=500)),
                ('idx', models.IntegerField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodo', to='cv.Cv')),
            ],
        ),
    ]
