# Generated by Django 2.1 on 2020-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0050_rodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='language',
            field=models.CharField(blank=True, default='pl', max_length=200),
        ),
    ]
